### ISSUE TITLE
Navigatie op Firefox en IE

### ISSUE THREAD

**Issue by mrombout** [Avans/Webdictaat-Javascript#2]
De navigatie op Firefox en IE ziet er niet helemaal netjes uit, zie de afbeelding hieronder.

![broken](https://cloud.githubusercontent.com/assets/651146/7363633/24cd16f6-ed7d-11e4-9cb9-3a23195ba96e.png)

Een snelle oplossing die ik kon vinden was om de `list-stye-position` definitie weg te halen en zelf een margin toe te voegen aan de list elementen. Het ziet er dan uit zoals op de onderstaande afbeelding. Let hierbij vooral op geselecteerde menu item dat er niet helemaal perfect uit ziet.

![quickfix](https://cloud.githubusercontent.com/assets/651146/7363689/c8b804ec-ed7d-11e4-8124-5d66c9c1cc68.png)

Maar er is vast wel een andere/betere oplossing voor dit probleem.

**Comment by PaulWagener** [comment]
Fixed in 82c682344b3d65ff6fc08b74beeedcc33493cce8
