### ISSUE TITLE
Inloggen werkt niet meer?

### ISSUE THREAD

**Issue by mrombout** [Avans/Webdictaat-Javascript#7]
Sinds de WEBS3 les van woensdag 29 april lijkt het inloggen niet meer te werken. Ik krijg een `Application Error` op de url `https://pointypony.herokuapp.com/auth/avans?returnUrl=http://avans.github.io/Webdictaat-Javascript/#/jquery/opdrachten.html`.

**Comment by mrombout** [comment]
De url `https://pointypony.herokuapp.com/Points` werkt ook niet. Is heel de app down misschien?

**Comment by PaulWagener** [comment]
Lijkt inmiddels weer te werken (of Stijn heeft het snel gefixt)
